anagrams: anagram.c
	gcc -g -Wall -o anagrams anagrams.c

test: anagram.c
	-./anagrams hello hello
	-./anagrams chicken nuggets
	-./anagrams cinema hello
	-./anagrams cinema iceman
	-./anagrams cream cheese
	-./anagrams acer acre
	-./anagrams aaabbbccc cabcabcab
	-./anagrams study_dusty dusty_study
	-./anagrams pam map
	-./anagrams CROCS hello
	-./anagrams HELLO hello

	
